apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx12
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx123
  template:
    metadata:
      labels:
        app: nginx123
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: ng-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: nginx123
  ports:
    - name: http
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-headless
  namespace: default
spec:
  type: NodePort
  selector:
    app: nginx123 #对应deployment的label
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80