spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/h2test/h2db1
    schema: classpath:schema.sql
    data: classpath:data.sql
    username: sa
    password: sa
    separator: ;
    sql-script-encoding: utf-8
    continue-on-error: false
    initialization-mode: always
  h2:
    console:
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/**/*Dao.xml
  type-aliases-package: com.nongfu.kakax.basemain

token:
  header: Authorization
  secret: 6F3931D35F0395DF82B032B8019AC57D
  expireTime: 15
